# Generated by Django 3.2.7 on 2021-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likedRecipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedrecipe',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
